### ISSUE TITLE
Wildcard % no longer working

### ISSUE THREAD

**Issue by arctic-ice-cool** [spatie/laravel-searchable#120]
Since v 1.10.0 and the support for "special characters" it has become apparent that splicing % into a query with spaces now returns a string like: `my\%search\%query` which doesn't work with the LIKE operator.

I've tracked down it's this line:
```
$searchTerm = addcslashes($searchTerm, "%_");
```

Within `ModelSearchAspect` that is causing it.

Is there a new way to specify the Wildcard character now?

Thanks

**Comment by arctic-ice-cool** [comment]
Hello,

This appears to be a limiting issue still with this package. Is it simply just not possible to search for the sentence in a single column, such as:

`This is a wonderful title` without every article being returned that contains either `This`, `is`, `a`, `wonderful`, `title` in it?

Previous versions of the package allowed this by replacing ` ` with `%` however since 1.10.0 this is no longer possible, I don't believe?

See also:
https://github.com/spatie/laravel-searchable/issues/61
https://github.com/spatie/laravel-searchable/issues/98

**Comment by danabrey** [comment]
Also struggling with this.

I think we need three different ways of adding a searchable attribute, rather than two:

`addSearchableAttribute()` should act as it does now, splitting by spaces and doing an `%word1% OR %word2%` query.

`addExactSearchableAttribute()` should also act as it does now, searching for exact `attribute = "whole search query"`.

But we need an addition 'phrase'-like search, which searches for `%whole search query%`, e.g. `addPhraseSearchableAttribute()`. I'd be happy to look at making a PR to add this if it's of interest @freekmurze
