### ISSUE TITLE
search deep related models

### ISSUE THREAD

**Issue by nenylukitasari** [spatie/laravel-searchable#31]
Hi. I've been working some projects and it has deep relationship eloquent models. I've read the readme how to create custom search by our own. Unfortunately, i can't solve it. I hope you could help. 
Here's my relationship models

version -> activity_type -> activity -> category -> notes -> sub1notes -> sub2notes

The eloquent is dependent by their id. I want to search string in all of those models inside the version tables which the version.status is active. I've tried to build custom search but it always shows all of the datas without filter the active version. Please help. Thank you.

**Comment by AlexVanderbist** [comment]
Hey, this is more an eloquent issue rather than an issue with this package. As you said: custom search aspect is the way to go but it's difficult to propose a query without knowing exactly how your models work. 

Personally I would use joins to add all required information to the version and then query those joined columns. Something like this (not everything is included):
```php
Version::join('activity_types', 'acitivity_types.version_id', 'versions.id')
->join('activities', 'activities.id', 'activity_types.activity_id')
->join('categories', 'categories.id', 'acitivities.category_id')
->join('notes', 'notes.id', 'categories.note_id')
->where('notes.text', $term);
```
